import os

CLAUDE_API_KEY = os.getenv("CLAUDE_API_KEY")
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")
INSTAGRAM_ACCESS_TOKEN = os.getenv("INSTAGRAM_ACCESS_TOKEN")
INSTAGRAM_USER_ID = os.getenv("INSTAGRAM_USER_ID")
VIDEO_OUTPUT_DIR = "videos"
